import { Workflow, WorkflowVersion, Execution, User } from '../types';

export const currentUser: User = {
  id: 'u1',
  name: 'Nexus Admin',
  email: 'ziadhatemdev@gmail.com',
  avatar: 'https://lh3.googleusercontent.com/a/default-user',
  role: 'admin',
};

export const mockWorkflows: Workflow[] = [
  {
    id: 'WFL-7724',
    name: 'Enterprise Data Sync Pipeline',
    description: 'Automated synchronization between primary PostgreSQL clusters and secondary analytical warehouses with real-time anomaly detection.',
    status: 'active',
    latestVersion: 'v2.4.1',
    lastModified: '2023-10-24T14:22:00Z',
    modifiedBy: 'alex.chen@nexus.io',
    category: 'Production',
    tags: ['Infrastructure', 'Postgres'],
    trigger: 'Cron Schedule (0 0 * * *)',
    resources: '2 CPU / 4GB RAM',
    owner: 'Sarah Jenkins',
    ownerAvatar: 'https://lh3.googleusercontent.com/a/default-user',
  },
  {
    id: 'WFL-7725',
    name: 'Customer Onboarding Sync',
    description: 'Syncs customer data from Salesforce to internal CRM via webhooks.',
    status: 'active',
    latestVersion: 'v2.4.1',
    lastModified: '2023-10-24T10:00:00Z',
    modifiedBy: 'alex.chen@nexus.io',
    category: 'Production',
    tags: ['Salesforce', 'Webhook'],
    trigger: 'Webhook Receiver',
    resources: '1 CPU / 2GB RAM',
    owner: 'Sarah Jenkins',
    ownerAvatar: 'https://lh3.googleusercontent.com/a/default-user',
  },
  {
    id: 'WFL-7726',
    name: 'Daily Revenue Aggregator',
    description: 'Aggregates daily revenue from Stripe and exports to Dataflow.',
    status: 'draft',
    latestVersion: 'v0.8.0-rc',
    lastModified: '2023-10-24T12:00:00Z',
    modifiedBy: 'sarah.smith@nexus.io',
    category: 'Infrastructure',
    tags: ['Stripe', 'Dataflow'],
    trigger: 'Schedule',
    resources: '2 CPU / 4GB RAM',
    owner: 'Marcus Thorne',
    ownerAvatar: 'https://lh3.googleusercontent.com/a/default-user',
  },
  {
    id: 'WFL-7727',
    name: 'Threat Detection Response',
    description: 'Monitors AWS GuardDuty for threats and triggers automated responses.',
    status: 'active',
    latestVersion: 'v4.1.2',
    lastModified: '2023-10-23T16:22:00Z',
    modifiedBy: 'system_orchestrator',
    category: 'Security',
    tags: ['AWS', 'GuardDuty'],
    trigger: 'CloudWatch Event',
    resources: '1 CPU / 1GB RAM',
    owner: 'Elena Rodriguez',
    ownerAvatar: 'https://lh3.googleusercontent.com/a/default-user',
  },
  {
    id: 'WFL-7728',
    name: 'Legacy Ticket Migrator',
    description: 'Migrates legacy tickets from Zendesk V1 to V2.',
    status: 'archived',
    latestVersion: 'v1.2.0',
    lastModified: '2023-09-12T09:00:00Z',
    modifiedBy: 'jordan.lee@nexus.io',
    category: 'Maintenance',
    tags: ['Zendesk', 'V1'],
    trigger: 'Manual',
    resources: '1 CPU / 2GB RAM',
    owner: 'Elena Rodriguez',
    ownerAvatar: 'https://lh3.googleusercontent.com/a/default-user',
  },
];

export const mockVersions: Record<string, WorkflowVersion[]> = {
  'WFL-7724': [
    {
      id: 'v1',
      versionId: 'v2.4.12-rc',
      status: 'active',
      publisher: 'Sarah Chen',
      publisherAvatar: 'https://lh3.googleusercontent.com/a/default-user',
      timestamp: '2023-10-24T14:22:00Z',
      notes: 'Optimized the data chunking size for bulk analytical warehouse uploads. Fixed memory leak in transformer node.',
    },
    {
      id: 'v2',
      versionId: 'v2.4.11-stable',
      status: 'legacy',
      publisher: 'Marcus Thorne',
      publisherAvatar: 'https://lh3.googleusercontent.com/a/default-user',
      timestamp: '2023-10-18T09:15:00Z',
      notes: 'Implemented new secret rotation for PostgreSQL connection strings.',
    },
    {
      id: 'v3',
      versionId: 'v2.4.10-patch',
      status: 'legacy',
      publisher: 'Sarah Chen',
      publisherAvatar: 'https://lh3.googleusercontent.com/a/default-user',
      timestamp: '2023-10-10T18:45:00Z',
      notes: 'Initial production release for Q3 reporting cycle.',
    },
  ],
};

export const mockExecutions: Record<string, Execution[]> = {
  'WFL-7724': [
    {
      id: 'e1',
      workflowId: 'WFL-7724',
      status: 'completed',
      timestamp: '2023-11-24T14:12:01Z',
      duration: '14.2s',
      recordsProcessed: 1244,
    },
    {
      id: 'e2',
      workflowId: 'WFL-7724',
      status: 'completed',
      timestamp: '2023-11-24T13:42:05Z',
      duration: '13.8s',
      recordsProcessed: 1021,
    },
    {
      id: 'e3',
      workflowId: 'WFL-7724',
      status: 'failed',
      timestamp: '2023-11-24T13:12:10Z',
      duration: '5.4s',
      recordsProcessed: 0,
      message: 'Retried step: Warehouse_Ingest • Warning: Schema Mismatch',
    },
  ],
};
